;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        browse-kill-ring
        dired-mark
        easy-kill
        kill-region
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        org-yank
        proced-mark
        tab-to-tab-stop
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        swiper-mc
        wdired-finish-edit
        ))
