;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        apply-macro-to-region-lines
        avy-copy-line
        browse-kill-ring
        calc-at-point-add
        crux-smart-kill-line
        dired-mark
        easy-kill
        indent-for-tab-command
        kill-region
        move-text-up
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        org-yank
        proced-mark
        sp-newline
        string-inflection-upcase
        tab-to-tab-stop
        typopunct-insert-typographical-dashes
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        repunctuate-sentences
        swiper-mc
        wdired-finish-edit
        wdired-next-line
        ))
