;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        org-delete-char
        org-self-insert-command
        tab-to-tab-stop
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        wdired-finish-edit
        counsel-M-x
        swiper-mc
        ))
